[project]
name = 'Virtual-Reality-Real-Estate-Development'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.virtual-property-nft]
path = 'contracts/virtual-property-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
